//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.07 at 03:39:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.fuse.jboss.com/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jboss.fuse.demo.jaxb;
